//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLaiXe
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationDetail
    {
        public int ID { get; set; }
        public Nullable<int> IdSpecification { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual Specification Specification { get; set; }
    }
}
